# Generated by Django 6.0.6 on 2026-07-02 03:46

import candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to=candidates.models.resume_upload_path)),
                ('skills', models.TextField(blank=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('education', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
